lintr::lint("~/Documents/Applications/staffing_demand_calculator/ui.R")
lintr::lint("~/Documents/Applications/staffing_demand_calculator/staff_projections.R")
lintr::lint("~/Documents/Applications/staffing_demand_calculator/server.R")
lintr::lint("~/Documents/Applications/staffing_demand_calculator/formula_for_cal.R")
lintr::lint("~/Documents/Applications/staffing_demand_calculator/functions/display_by_mode.R")
lintr::lint("~/Documents/Applications/staffing_demand_calculator/functions/calculator_staff_needs.R")
